/*
 * 
 */
package club.notrighteous.manjaro.ui;

import club.notrighteous.manjaro.CommandUtil;
import club.notrighteous.manjaro.config.ConfigUtil;
import club.notrighteous.manjaro.ui.InfoUI;
import com.formdev.flatlaf.FlatDarkLaf;
import java.util.ArrayList;

/**
 *
 * @author migo
 */
public class BootUI extends javax.swing.JFrame {

    /**
     * Creates new form BootUI
     */
    public BootUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainToolbar = new javax.swing.JToolBar();
        aboutToolbarBtn = new javax.swing.JButton();
        debugToolbarBtn = new javax.swing.JButton();
        exitToolbarBtn = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        jdkVersionsBox = new javax.swing.JComboBox<>();
        setJdkBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JManjaro JDK");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mainToolbar.setRollover(true);

        aboutToolbarBtn.setText("About");
        aboutToolbarBtn.setFocusable(false);
        aboutToolbarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aboutToolbarBtn.setMargin(new java.awt.Insets(2, 16, 2, 16));
        aboutToolbarBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        aboutToolbarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutToolbarBtnActionPerformed(evt);
            }
        });
        mainToolbar.add(aboutToolbarBtn);

        debugToolbarBtn.setText("Debug");
        debugToolbarBtn.setFocusable(false);
        debugToolbarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        debugToolbarBtn.setMargin(new java.awt.Insets(2, 16, 2, 16));
        debugToolbarBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        debugToolbarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debugToolbarBtnActionPerformed(evt);
            }
        });
        mainToolbar.add(debugToolbarBtn);

        exitToolbarBtn.setText("Exit");
        exitToolbarBtn.setFocusable(false);
        exitToolbarBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitToolbarBtn.setMargin(new java.awt.Insets(2, 16, 2, 16));
        exitToolbarBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exitToolbarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitToolbarBtnActionPerformed(evt);
            }
        });
        mainToolbar.add(exitToolbarBtn);

        contentPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("JDK Information:"));

        setJdkBtn.setText("Set JDK as Default...");
        setJdkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setJdkBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdkVersionsBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(setJdkBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdkVersionsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setJdkBtn)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        populateJdks();
    }//GEN-LAST:event_formWindowOpened

    private void debugToolbarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debugToolbarBtnActionPerformed
    
    }//GEN-LAST:event_debugToolbarBtnActionPerformed

    private void exitToolbarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitToolbarBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitToolbarBtnActionPerformed

    private void aboutToolbarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutToolbarBtnActionPerformed
        InfoUI.displayInfo("Created by Migo for own usage");
    }//GEN-LAST:event_aboutToolbarBtnActionPerformed

    private void setJdkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setJdkBtnActionPerformed
        String selectedJdk = jdkVersionsBox.getItemAt(jdkVersionsBox.getSelectedIndex());
        if(selectedJdk.contains("default")) {
            InfoUI.displayError("JDK already default");
        } else {
            if(!selectedJdk.isEmpty()) {
                CommandUtil.setJdkDefault(selectedJdk);
            } else {
                InfoUI.displayError("Empty jdk selection");
            }
            populateJdks();
        }
    }//GEN-LAST:event_setJdkBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    javax.swing.UIManager.setLookAndFeel(new FlatDarkLaf());
                    break;
            }
        } catch(Exception ex) {
            
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BootUI().setVisible(true);
            }
        });
    }
    
    public void populateJdks() {
        ArrayList<String> jdks = CommandUtil.getJdkInstalled();
        jdkVersionsBox.removeAllItems();
        for(String jdk : jdks) {
            jdkVersionsBox.addItem(jdk);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutToolbarBtn;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton debugToolbarBtn;
    private javax.swing.JButton exitToolbarBtn;
    private javax.swing.JComboBox<String> jdkVersionsBox;
    private javax.swing.JToolBar mainToolbar;
    private javax.swing.JButton setJdkBtn;
    // End of variables declaration//GEN-END:variables
}
